### ISSUE TITLE
Enable gui authentication

### ISSUE THREAD

**Issue by bchatelard** [scaleway-community/scaleway-syncthing#6]
http://docs.syncthing.net/users/syncthing.html?highlight=auth#cmdoption-gui-authentication

**Comment by vikbez** [comment]
you can activate the auth within syncthing GUI

**Comment by bchatelard** [comment]
I think this should be enabled by default, and you should be able to retrieve the login/password in the motd (which is also missing)

**Comment by vikbez** [comment]
The users need simplicity, and does not necessarily know how/want to do a ssh to the server.

When you first boot a syncthing instance, there is nothing on it, and require validation from both devices to add your data on it.
It is thus safe to first let auth deactivated, and let the user configure himself the authentication.

This can maybe be asked in our community for more input.

**Comment by moul** [comment]
@QuentinPerez @bchatelard @vikbez @aimxhaisse what do you think about: https://github.com/scaleway/api.scaleway.com/issues/17 ?

**Comment by moul** [comment]
@QuentinPerez @bchatelard @aimxhaisse @brmzkw: something to add ?
